---
- name: add the opentofu apt gpg key
  become: yes
  apt_key:
    url: "https://get.opentofu.org/opentofu.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/opentofu.gpg

- name: add the opentofu-repo apt gpg key
  become: yes
  apt_key:
    url: "https://packages.opentofu.org/opentofu/tofu/gpgkey"
    state: present
    keyring: /etc/apt/trusted.gpg.d/opentofu-repo.gpg

- name: the opentofu apt ppa and src ppa
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
  - "deb [signed-by=/etc/apt/trusted.gpg.d/opentofu.gpg,/etc/apt/trusted.gpg.d/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main"
  - "deb-src [signed-by=/etc/apt/trusted.gpg.d/opentofu.gpg,/etc/apt/trusted.gpg.d/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main"

- name: install opentofu package
  become: yes
  package:
    name:
    - tofu
    state: latest
    update_cache: yes
