# Blackbox exporter details
blackbox_exporter_version: 0.23.0
blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: []
  tcp_connect:
    prober: tcp
    timeout: 5s
  grpc_plain:
    prober: grpc
    grpc:
      tls: false

# OTel Collector details
otelcol_receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      global:
        evaluation_interval: 15s
        scrape_interval: 15s
        scrape_timeout: 10s

      scrape_configs:
      - job_name: "grafana"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:3000"
      - job_name: "node"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9100"
      - job_name: "otel-collector"
        static_configs:
          - targets: ["localhost:8888"]
      - job_name: "prometheus"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9090"
      - job_name: "blackbox"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9115"

otelcol_exporters:
  prometheus:
    endpoint: "localhost:8889"
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true

otelcol_service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]
  extensions: [health_check, pprof, zpages]

# Prometheus details
prometheus_web_listen_address: 0.0.0.0:9090
prometheus_scrape_configs:
  - job_name: "otelcol"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "localhost:8889"
    relabel_configs:
      - source_labels: [exported_job]
        target_label: job
  - job_name: "blackbox-http"
    metrics_path: "/probe"
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - "localhost:8080"
        labels:
          probe: calibre
      - targets:
          - "127.0.0.1:3000"
        labels:
          probe: grafana
      - targets:
          - "127.0.0.1:9090"
        labels:
          probe: prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"
  - job_name: "blackbox-grpc"
    metrics_path: "/probe"
    params:
      module:
        - grpc_plain
    static_configs:
      - targets:
          - "127.0.0.1:14250"
        labels:
          probe: jaeger
      - targets:
          - "127.0.0.1:4317"
        labels:
          probe: otelcol
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"
