# Blackbox exporter details
blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: []
  tcp_connect:
    prober: tcp
    timeout: 5s

# OTel Collector details
otelcol_receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      global:
        evaluation_interval: 15s
        scrape_interval: 15s
        scrape_timeout: 10s

      scrape_configs:
      - job_name: "blackbox"
        metrics_path: "/probe"
        params:
          module:
            - http_2xx
        static_configs:
          - targets:
              - "localhost:8080"
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: "localhost:9115"
      - job_name: "grafana"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:3000"
      - job_name: "node"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9100"
      - job_name: "otel-collector"
        static_configs:
          - targets: ["localhost:8888"]
      - job_name: "prometheus"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9090"

# Prometheus details
prometheus_web_listen_address: 0.0.0.0:9090
prometheus_scrape_configs:
  - job_name: "otelcol"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "localhost:8889"
    relabel_configs:
      - source_labels: [exported_job]
        target_label: job
