---
- name: install packages for building lpass from source
  become: yes
  apt:
    name:
    - openssl
    - libcurl4-openssl-dev
    - libxml2
    - libssl-dev
    - libxml2-dev
    - pinentry-curses
    - xclip
    state: present
