---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: checkout_latest_lpass
  git: repo=git@github.com:lastpass/lastpass-cli.git
       dest={{ src }}/github.com/lastpass/lastpass-cli
       accept_hostkey=yes update=yes

- name: build_lpass
  command: chdir={{ src }}/github.com/lastpass/lastpass-cli /usr/bin/make

- name: install_lpass
  sudo: yes
  command: chdir={{ src }}/github.com/lastpass/lastpass-cli /usr/bin/make install
