---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: checkout_latest_lpass
  git:
    repo: git@github.com:lastpass/lastpass-cli.git
    dest: "{{ lpass_src_path }}"
    update: yes

- name: build_lpass
  command:
    chdir: "{{ lpass_src_path }}"
    command: /usr/bin/make

- name: install_lpass
  become: yes
  command:
    chdir: "{{ lpass_src_path }}"
    command: /usr/bin/make install
