---
- name: install_package_list
  become: yes
  yum: name={{ item }} state=present update_cache=yes
  with_items:
      - openssl-devel
      - libcurl-devel
      - libxml2-devel
      - pinentry-curses
      - xclip
      - gcc
