---
- name: install packages for building lpass from source
  become: yes
  yum:
    name:
    - openssl-devel
    - libcurl-devel
    - libxml2-devel
    - pinentry-curses
    - xclip
    - gcc
    state: present
