---
- name: install golang package
  become: yes
  package:
    name:
      - golang
    state: latest
    update_cache: yes

- name: Insert/Update .bash with golang env vars
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    marker: "# {mark} golang"
    block: |
      export GOPATH=$HOME
      export PATH=$PATH:/usr/local/go/bin:$HOME/bin
