otelcol_version: latest
otelcol_arch:
  x86_64: amd64
  aarch64: arm64

otelcol_extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

otelcol_receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 15s
          static_configs:
            - targets: ["localhost:8888"]

otelcol_processors:
  batch:

otelcol_exporters:

otelcol_service:
