otelcol_version: latest
otelcol_arch:
  x86_64: amd64
  aarch64: arm64

otelcol_extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

otelcol_receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 15s
          static_configs:
            - targets: ["localhost:8888"]

otelcol_processors:
  batch:

otelcol_exporters:
  prometheus:
    endpoint: "localhost:8889"
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true

otelcol_service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]
  extensions: [health_check, pprof, zpages]
