---
- name: Install desktop environment + applications
  hosts: all
  roles:
  - calibre
  - fonts
  - terminator
  #- signal
  #- { role: common, tags: ["common"] }
  #- { role: chrome, tags: ["chrome"] }
  #- { role: spotify, tags: ["spotify"] }
  #- { role: i3, tags: ["i3"] }
  #- { role: xmind, tags: ["xmind"] }
