---
- name: install monitoring infra
  gather_facts: yes
  hosts: infra
  roles:
  - name: grafana
    tags:
      - traces
      - metrics
      - logs
  - name: cloudalchemy.prometheus
    tags:
      - metrics
  - name: blackbox_exporter
    tags:
      - metrics
  - name: jaeger
    tags:
      - traces
  - name: loki
    tags:
      - logs
  - name: promtail
    tags:
      - logs
