---
- name: install monitoring agents
  gather_facts: yes
  hosts: all
  roles:
  - name: node_exporter
    tags:
    - metrics
  - name: fluentd
    tags: 
    - logs
  - name: otelcol
    tags:
    - logs
