---
- name: install monitoring agents
  gather_facts: yes
  hosts: all
  roles:
  - name: node_exporter
    tags:
    - node_exporter
    - metrics
  - name: fluentd
    tags:
    - fluentd
    - logs
  - name: otel
    tags:
    - otel
    - traces
  - name: otelcol
    tags:
    - otel
    - traces
    - metrics
    - logs
