---
- name: execute one/more/all roles
  gather_facts: yes
  hosts: all
  pre_tasks:
  - name: "load vars from ~/.playbooks.yml"
    include_vars: "{{ ansible_user_dir }}/.playbooks.yml"
    tags:
    - always

  roles:
  - {'name': 'utilities', 'tags': ['utilities', 'system']}
  - {'name': 'bashrc', 'tags': ['bashrc', 'system']}
  - {'name': 'inputrc', 'tags': ['inputrc', 'system']}
