---
- name: execute one/more/all roles
  gather_facts: yes
  hosts: localhost
  collections:
  - nicr9.firefox
  pre_tasks:
  - name: "load vars from ~/.playbooks.yml"
    include_vars: "{{ ansible_user_dir }}/.playbooks.yml"
    tags:
    - always

  roles:
  - {'name': 'utilities', 'tags': ['utilities', 'system']}
  - {'name': 'bashrc', 'tags': ['bashrc', 'system']}
  - {'name': 'inputrc', 'tags': ['inputrc', 'system']}
  - {'name': 'pip', 'tags': ['pip', 'development']}
  - {'name': 'awscli', 'tags': ['awscli', 'development']}
  - {'name': 'fzf', 'tags': ['fzf', 'development']}
  - {'name': 'nvim', 'tags': ['nvim', 'development']}
  - name: nvim-plugin
    vars:
      repo: python-mode/python-mode
      options:
        for: python
        branch: develop
    tags:
    - development
    - nvim_python
  - name: ssh
    vars:
      ssh_keypair:
        comment: "{{ personal_email }}"
    tags:
    - development
    - ssh
  - name: git_config
    vars:
      git_config_user:
        name: "{{ personal_full_name }}"
        email: "{{ personal_email }}"
    tags:
    - development
    - git
  - name: github
    vars:
      github_config_user:
        name: "{{ personal_full_name }}"
        email: "{{ personal_email }}"
      github_keypair:
        comment: "{{ personal_email }}"
    tags:
    - development
    - github
  - {'name': 'terraform', 'tags': ['terraform', 'development']}
  - {'name': 'tmux', 'tags': ['tmux', 'development']}
  - {'name': 'golang', 'tags': ['golang', 'development']}
  - {'name': 'pandoc', 'tags': ['pandoc', 'development']}
  - {'name': 'nodejs', 'tags': ['nodejs', 'development']}
  - {'name': 'docker', 'tags': ['docker', 'development']}
  - {'name': 'semgrep', 'tags': ['semgrep', 'development']}
  - {'name': 'poetry', 'tags': ['poetry', 'development']}
  - {'name': 'java8', 'tags': ['java8', 'development']}
  - {'name': 'skopeo', 'tags': ['skopeo', 'development']}
  - {'name': 'steam', 'tags': ['steam', 'games']}
  - {'name': 'terminator', 'tags': ['terminator', 'development']}
  - {'name': 'esp-idf', 'tags': ['esp-idf', 'esp', 'development']}
  - {'name': 'scrcpy', 'tags': ['scrcpy']}
  - {'name': 'bettercap', 'tags': ['bettercap']}
  - {'name': 'apktool', 'tags': ['apktool']}
  - {'name': 'jadx', 'tags': ['jadx']}
  - {'name': 'ghidra', 'tags': ['ghidra']}
  - {'name': 'koreader', 'tags': ['koreader']}
  - {'name': 'redis', 'tags': ['redis']}
  - {'name': 'wireshark', 'tags': ['wireshark']}
  - {'name': 'sway', 'tags': ['sway']}
  - {'name': 'mako', 'tags': ['mako']}
  - {'name': 'waybar', 'tags': ['waybar']}
  - {'name': 'feh', 'tags': ['feh']}
  - {'name': 'fonts', 'tags': ['fonts', 'system']}
  - {'name': 'yt-dlp', 'tags': ['yt-dlp']}
  - {'name': 'hugo', 'tags': ['hugo']}
  - {'name': 'rclone', 'tags': ['rclone']}
  - {'name': 'jq', 'tags': ['jq']}
  - {'name': 'vlc', 'tags': ['vlc']}
  - {'name': 'kicad', 'tags': ['kicad', 'engineering']}
  - {'name': 'gimp', 'tags': ['gimp', 'desktop']}
  - {'name': 'inkscape', 'tags': ['inkscape', 'desktop']}
  - {'name': 'libreoffice', 'tags': ['libreoffice', 'desktop']}
  - {'name': 'transmission', 'tags': ['transmission', 'desktop']}
  - {'name': 'signal', 'tags': ['signal', 'desktop'], 'vars': {'signal_distribution_release': 'xenial'}}
  - {'name': 'handbrake', 'tags': ['handbrake', 'media']}
  - {'name': 'nicr9.firefox.browser', 'tags': ['firefox', 'desktop']}
  - {'name': 'syncthing', 'tags': ['syncthing', 'storage']}
  - {'name': 'gparted', 'tags': ['gparted', 'storage']}
  - {'name': 'packer', 'tags': ['packer']}
  - {'name': 'dconf', 'tags': ['dconf', 'system']}
  - {'name': 'tensorflow', 'tags': ['tensorflow', 'development']}
  - {'name': 'nfsd', 'tags': ['nfsd', 'system']}
  - {'name': 'dotnetsdk', 'tags': ['dotnetsdk', 'development']}
  - {'name': 'synapse', 'tags': ['synapse', 'matrix', 'messaging']}
  - {'name': 'jsonnet', 'tags': ['jsonnet', 'development']}
  - {'name': 'obsidian', 'tags': ['obsidian', 'development']}
  - {'name': 'freecad', 'tags': ['freecad', 'engineering']}
  - {'name': 'opentofu', 'tags': ['opentofu', 'cicd']}
  - {'name': 'flux', 'tags': ['flux', 'cicd']}
  - {'name': 'mgba', 'tags': ['mgba', 'games']}
  - {'name': 'orcaslicer', 'tags': ['orcaslicer', 'engineering']}
  - {'name': 'beets', 'tags': ['beets', 'music']}
  - {'name': 'tailscale', 'tags': ['tailscale', 'network']}
  - {'name': 'moonlight', 'tags': ['moonlight', 'games']}
  - {'name': 'vscode', 'tags': ['vscode', 'development']}
