---
- name: preflight
  gather_facts: no
  hosts: all
  tasks:
  - name: "load vars from {{ lookup('env', 'HOME') }}/.playbooks.yml"
    include_vars: "{{ lookup('env', 'HOME') }}/.playbooks.yml"
  tags:
  - always

- name: system setup; prepare ansible environment
  become: yes
  hosts: all
  pre_tasks:
  - name: install yum packages required by Ansible modules
    yum:
      name: "{{ item }}"
    loop:
    - zip
    - unzip
    when: ansible_os_family == "RedHat"
  - name: install apt packages required by Ansible modules
    apt:
      name: "{{ item }}"
    loop:
    - zip
    - unzip
    when: ansible_os_family == "Debian"
  roles:
  - bashrc
  - utilities
  #- ansible
  tags:
  - system

- name: set up development tools
  hosts: all
  roles:
  - pip
  - awscli
  - fzf
  - nvim
  - name: ssh
    vars:
      ssh_keypair:
        comment: "{{ personal_email }}"
  - name: git
    vars:
      git_config_user:
        name: "{{ personal_full_name }}"
        email: "{{ personal_email }}"
  - github
  - terraform
  - tmux
  - golang
  - pandoc
  - nodejs
  #- docker
  tags:
  - development

- name: Install desktop environment + applications
  hosts: all
  roles:
  - calibre
  - fonts
  - terminator
  - firefox
  #- signal
  #- { role: common, tags: ["common"] }
  #- { role: chrome, tags: ["chrome"] }
  #- { role: spotify, tags: ["spotify"] }
  #- { role: i3, tags: ["i3"] }
  #- { role: xmind, tags: ["xmind"] }
  tags:
  - desktop
