---
- name: preflight
  gather_facts: yes
  hosts: all
  tasks:
  - name: "load vars from ~/.playbooks.yml"
    include_vars: "{{ ansible_user_dir }}/.playbooks.yml"
  tags:
  - always

- name: system setup; prepare ansible environment
  become: yes
  hosts: all
  roles:
  - bashrc
  - inputrc
  - utilities
  - fzf
  - tmux
  - dconf
  - fonts
  tags:
  - system

- name: set up monitoring agents
  hosts: all
  roles:
  - role: cloudalchemy.node-exporter
  - role: otelcol
  tags:
  - monitoring

- name: Install desktop environment
  hosts: all
  roles:
  - sway
  - tofi
  - waybar
  tags:
  - desktop

- name: Install applications
  hosts: all
  roles:
  - terminator
  - firefox
  #- signal
  tags:
  - apps
