---
- name: base_desktop
  hosts: local
  roles:
  - { role: lpass, tags:["lpass"] }
  - { role: common, tags:["common"] }
  - { role: docker, tags:["docker"] }
  - { role: fzf, tags:["fzf"] }
  - { role: spotify, tags:["spotify"] }
  - { role: i3, tags:["i3"] }
  - { role: vim, tags:["vim"] }
  - { role: saltstack, tags:["saltstack"] }
  - { role: syncthing, tags:["syncthing"] }
  - { role: fonts, tags:["fonts"] }
  - { role: xmind, tags:["xmind"] }
