# vim:ft=ansible:
---
# This playbook applies my environment setup to localhost

- name: base_desktop
  hosts: local
  roles:
  - lpass
  - common
  - docker
  - fzf
  - spotify
  - i3
  - vim
  - saltstack
  - fonts
