---
- name: base_desktop
  hosts: local
  roles:
  - fzf
  - pip
  - nvim
  - git
  - ansible
  - terraform
  #- docker
  #- { role: common, tags: ["common"] }
  #- { role: chrome, tags: ["chrome"] }
  #- { role: spotify, tags: ["spotify"] }
  #- { role: i3, tags: ["i3"] }
  #- { role: saltstack, tags: ["saltstack"] }
  #- { role: syncthing, tags: ["syncthing"] }
  #- { role: fonts, tags: ["fonts"] }
  #- { role: xmind, tags: ["xmind"] }
