---
- name: system setup; prepare ansible environment
  hosts: all
  pre_tasks:
  - name: install yum packages required by Ansible modules
    yum:
      name: "{{ item }}"
    loop:
    - unzip
    when: ansible_os_family == "RedHat"
  - name: install apt packages required by Ansible modules
    apt:
      name: "{{ item }}"
    loop:
    - unzip
    when: ansible_os_family == "Debian"
  roles: []
  #- ansible
