---
- name: system setup; prepare ansible environment
  become: yes
  hosts: all
  pre_tasks:
  - name: install yum packages required by Ansible modules
    yum:
      name: "{{ item }}"
    loop:
    - zip
    - unzip
    when: ansible_os_family == "RedHat"
  - name: install apt packages required by Ansible modules
    apt:
      name: "{{ item }}"
    loop:
    - zip
    - unzip
    when: ansible_os_family == "Debian"
  roles:
  - bashrc
  #- ansible
