---
- include_tasks: "Debian.yml"

- name: install td-agent packages
  become: yes
  package:
    name:
    - td-agent
    state: latest
    update_cache: yes
  notify:
  - restart td-agent

- name: configure td-agent
  become: yes
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    mode: 0644
    owner: root
    group: root
  tags:
  - config
  notify:
  - restart td-agent

- name: create conf.d/
  become: yes
  file:
    path: /etc/td-agent/conf.d
    state: directory
    mode: 0644
    owner: root
    group: root
  tags:
  - config

- name: copy custom config to conf.d/
  become: yes
  template:
    src: "{{ item }}"
    dest: "/etc/td-agent/conf.d/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: 0644
    owner: root
    group: root
  with_fileglob: "{{ fluentd_config_paths }}"
  tags:
  - config
  notify:
  - restart td-agent
