---
- name: install dconf-editor
  become: yes
  package:
    name:
    - dconf-service
    - dconf-cli
    - dconf-editor
    state: present

- name: modify misc dconf settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ dconf_config | dict2items }}"
  loop_control:
    label: "{{ item.key }} = {{ item.value }}"
