---
nginx_user: root
nginx_group: root

nginx_access_log: combined
nginx_error_log: ''

nginx_default_site:
  tls:
    enabled: false
  root: /var/www/html
  index: index.nginx-debian.html
  server_name: '_'
