---
- name: add Signal's apt key
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc

- name: add Signal's apt repository
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal-xenial

- name: install Signal Desktop
  apt:
    name: signal-desktop
