---
- name: set misc environment variables
  blockinfile:
    path: ~/.bashrc
    block: |-
      {% for key, val in bashrc_variables.items() %}
      export {{ key }}={{ val }}
      {% endfor %}
    marker: "# {mark} misc environment variables"
