---
- name: set misc environment variables
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |-
      export PATH={{ bashrc_path_combined | join(':') }}
      export CDPATH={{ bashrc_cdpath_combined | join(':') }}
      {% for key, val in bashrc_variables.items() %}
      export {{ key }}={{ val }}
      {% endfor %}
      {% for key, val in bashrc_aliases.items() %}
      alias {{ key }}='{{ val }}'
      {% endfor %}
    marker: "# {mark} misc environment variables"
