---
- name: set misc environment variables
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    block: |-
      {% for key, val in bashrc_variables.items() %}
      export {{ key }}={{ val }}
      {% endfor %}
      export CDPATH={{ bashrc_cdpath | join(':') }}
    marker: "# {mark} misc environment variables"
