- name: upgrade_pip
  become: yes
  pip:
    name: pip
    extra_args: --upgrade

- name: install_pip_packages
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - awscli
    - boto
    - botocore
    - boto3
    - yum
