---
- name: add Packer's apt key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"

- name: add Packer's apt repository
  apt_repository:
    repo: "deb [arch={{ packer_arch[ansible_architecture] }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

- name: install Packer
  apt:
    name: packer
    update_cache: yes
