---
- name: user/group setup
  when: calibre_user == "calibre"
  block:
  - name: create calibre system group
    become: yes
    group:
      name: calibre
      system: true
      state: present

  - name: create calibre system user
    become: yes
    user:
      name: calibre
      system: true
      shell: "/usr/sbin/nologin"
      group: calibre
      createhome: false
      home: /opt/home/calibre

  - name: add user to calibre group (requires user to log out/in)
    become: yes
    user:
      name: "{{ ansible_user }}"
      groups: calibre
      append: yes

- name: create calibre data directory
  become: yes
  file:
    path: "{{ calibre_library_dir }}"
    state: directory
    owner: "{{ calibre_user }}"
    group: "{{ calibre_user }}"
    mode: 0755

- name: install Calibre
  become: yes
  package:
    name:
    - calibre
    state: present

- name: create systemd service unit
  become: yes
  template:
    src: calibre.service.j2
    dest: /etc/systemd/system/calibre.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart calibre
