---
- name: user/group setup
  become: yes
  when: calibre_system_user
  block:
  - name: create calibre system group
    group:
      name: "{{ calibre_group }}"
      system: true
      state: present

  - name: create calibre system user
    user:
      name: "{{ calibre_user }}"
      system: true
      shell: "/usr/sbin/nologin"
      group: "{{ calibre_group }}"
      createhome: false
      home: /opt/home/calibre

  - name: add user to calibre group (requires user to log out/in)
    user:
      name: "{{ ansible_user }}"
      groups: "{{ calibre_group }}"
      append: yes

- name: create calibre data directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ calibre_user }}"
    group: "{{ calibre_group }}"
    mode: 0770
  loop:
  - "{{ calibre_library_dir }}"
  - "{{ calibre_import_dir }}"

- name: install Calibre
  become: yes
  package:
    name:
    - calibre
    state: present

- name: install book import script
  become: yes
  copy:
    src: "calibre-import.py"
    dest: "/usr/local/bin/calibre-import.py"
    owner: root
    group: "{{ calibre_group }}"
    mode: 0750

- name: create calibre.service unit
  become: yes
  template:
    src: calibre.service.j2
    dest: /etc/systemd/system/calibre.service
    owner: root
    group: "{{ calibre_group }}"
    mode: 0640
  notify:
  - restart calibre.service

- include: "import-system.yml"
  when: calibre_system_user
- include: "import-user.yml"
  when: not calibre_system_user
