---
- name: ensure ~/.ssh exists
  file:
    path: "{{ home }}/.ssh"
    state: directory

- name: ensure keypair exists
  openssh_keypair:
    path: "{{ home }}/.ssh/{{ ssh_keypair_combined.name }}"
    type : "{{ ssh_keypair_combined.type }}"
    size: "{{ ssh_keypair_combined.size }}"
    comment: "{{ ssh_keypair_combined.comment }}"
  register: keypair

- name: configure ssh
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    create: yes
    mode: 0600
    marker: '# {mark} misc ssh targets'
    block: |-
      {% for host, item in ssh_config_combined.items() %}
      host {{ host }}
      {% for key, val in item.items() %}
       {{ key }} {{ val }}
      {% endfor %}
      {% endfor %}

- name: populate known_hosts
  known_hosts:
    name: "{{ item.key }}"
    key: "{% if item.value != '' %}{{ item.value }}{% else %}{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.key | quote) }}{% endif %}"
    hash_host: yes
  loop: "{{ ssh_pubkeys_combined }}"

- name: authorize key with GitHub
  github_key:
    name: "access key for {{ ansible_host }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ keypair.public_key }}'
  when:
  - github_access_token is defined
  - github_access_token != ''
