---
- name: ensure ~/.ssh exists
  file:
    path: "{{ home }}/.ssh"
    state: directory

- name: ensure keypair exists
  openssh_keypair:
    path: "{{ home }}/.ssh/{{ ssh_key_name }}"
    type : "{{ ssh_key_type }}"
    size: 4096
    comment: "{{ ssh_key_comment }}"
  register: keypair

# TODO: copy ssh config template

- name: "add {{ item.key }} to known_hosts"
  known_hosts:
    name: "{{ item.key }}"
    key: "{% if item.value != '' %}{{ item.value }}{% else %}{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.key | quote) }}{% endif %}"
    hash_host: yes
  loop: "{{ lookup('dict', ssh_pubkey_defaults | combine(ssh_pubkeys) ) }}"

- name: authorize key with GitHub
  github_key:
    name: "access key for {{ ansible_host }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ keypair.public_key }}'
  when:
  - github_access_token is defined
  - github_access_token != ''
  - keypair.changed
