---
- name: install prerequisites
  become: yes
  package:
    name:
    - flex
    - bison
    - gperf
    - cmake
    - ninja-build
    - ccache
    - libffi-dev
    - libssl-dev
    - dfu-util
    - libusb-1.0-0
    state: latest

- name: download ESP IoT Development Framework
  git:
    repo: https://github.com/espressif/esp-idf.git
    recursive: yes
    dest: "{{ ansible_user_dir }}/src/github.com/espressif/esp-idf"
    version: master

- name: run install script
  command:
    cmd: "./install.sh esp32"
    chdir: "{{ ansible_user_dir }}/src/github.com/espressif/esp-idf"

- name: create alias for the esp-idf virtual env
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: alias esp32='. $HOME/src/github.com/espressif/esp-idf/export.sh'
    marker: "# {mark} ESP-IDF virtual env"
