---
- name: install semgrep package
  become: yes
  pip:
    name:
    - semgrep
    state: present

- name: install OCaml tooling
  package:
    name: opam
    state: present

- name: check out semgrep code
  git:
    repo: https://github.com/returntocorp/semgrep.git
    dest: "{{ ansible_user_dir }}/src/github.com/returntocorp/semgrep"
    state: present
