- name: add the spotify apt gpg keys
  become: yes
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_0D811D58.gpg"
    state: present

- name: add the spotify ppa
  become: yes
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    state: present

- name: Install package list
  become: yes
  apt:
    name: spotify-client
    state: latest
    update_cache: yes
