- name: add the spotify apt gpg keys
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
    state: present
  loop:
  - '94558F59'
  - 'D2C19886'

- name: add the spotify ppa
  become: yes
  apt_repository:
    repo: 'deb http://repository.spotify.com testing non-free'
    state: present

- name: Install package list
  become: yes
  apt:
    name: spotify-client
    state: latest
    update_cache: yes
