---
- name: add spotify yum repo
  become: yes
  yum_repository:
    name: "spotify"
    description: "3rd party yum repo for installing Spotify."
    baseurl: "http://negativo17.org/repos/spotify/epel-$releasever/$basearch/"
    gpgcheck: yes
    gpgkey: "http://negativo17.org/repos/RPM-GPG-KEY-slaanesh"

- name: install spotify rpm
  become: yes
  yum:
    name: spotify-client
    state: present
    update_cache: yes
