- name: del_yum_repo
  become: yes
  yum_repository:
    name: "spotify"
    description: "3rd party yum repo for installing Spotify."
    baseurl: "http://negativo17.org/repos/spotify/fedora-$releasever/$basearch/"
    gpgcheck: yes
    gpgkey: "http://negativo17.org/repos/RPM-GPG-KEY-slaanesh"
    state: absent

- name: add_yum_repo
  become: yes
  yum_repository:
    name: "spotify"
    description: "3rd party yum repo for installing Spotify."
    baseurl: "http://negativo17.org/repos/spotify/epel-$releasever/$basearch/"
    gpgcheck: yes
    gpgkey: "http://negativo17.org/repos/RPM-GPG-KEY-slaanesh"

- name: install_rpm
  become: yes
  yum:
    name: spotify-client
    state: present
    update_cache: yes
