---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: create i3 directories
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  with_items:
    - .i3
    - .config/i3status
    - wallpaper

- name: install i3 config
  file:
    src: "{{ dotfiles }}/doti3/config"
    dest: "{{ ansible_user_dir }}/.i3/config"
    state: link

- name: setup rotating wallpapers
  cron:
    name: "rotate_wallpapers"
    job: 'DISPLAY=:0.0 feh --bg-max "$(find ~/wallpaper/|shuf -n1)"'
