---
- name: install_package_list
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dmenu
    - feh
    - i3
    - i3status

- name: create_dirs
  file:
    path: "{{ home }}/{{ item }}"
    state: directory
  with_items:
    - .i3
    - wallpaper

- name: config_files
  file:
    src: "{{ dotfiles }}/doti3/config"
    dest: "{{ home }}/.i3/config"
    state: link

- name: rotate_wallpapers
  cron:
    name: "rotate_wallpapers"
    job: 'DISPLAY=:0.0 feh --bg-max "$(find ~/wallpaper/|shuf -n1)"'
