---
- name: install_package_list
  sudo: yes
  apt: name={{ item }} state=present
  with_items: apt_packages

- name: create_dirs
  file: path={{ item }} state=directory
  with_items: dirs

- name: config_files
  file: src={{ dotfiles }}/{{ item.src }}
        dest={{ home }}/{{ item.dest }}
        state=link
  with_items: config_files

- name: rotate_wallpapers
  cron: name="rotate_wallpapers"
        job='DISPLAY=:0.0 feh --bg-max "$(find ~/wallpaper/|shuf -n1)"'
