---
- import_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- import_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: create i3 directories
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  loop:
    - .i3
    - .config/i3status
    - wallpaper

- name: install i3 config
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
  loop:
  - { src: 'doti3config', dest: '.i3/config' }
  - { src: 'doti3statusconfig', dest: '.config/i3status/config' }

- name: setup rotating wallpapers
  cron:
    name: "rotate_wallpapers"
    job: 'DISPLAY=:0.0 feh --bg-max "$(find ~/wallpaper/|shuf -n1)"'
