---
- name: checkout source
  git:
    repo: "https://github.com/i3/i3.git"
    dest: "{{ i3_src_path }}"
    version: "4.12"

- name: install packages for building i3 from source
  become: yes
  yum:
    name:
    - dmenu
    - pkgconfig
    - libxcb
    - libxcb-devel
    - xcb-util
    - xcb-util-devel
    - libxkbcommon
    - libxkbcommon-devel
    - xcb-util-cursor
    - xcb-util-cursor-devel
    - xcb-util-wm
    - xcb-util-wm-devel
    - xcb-util-keysyms
    - xcb-util-keysyms-devel
    - libev
    - libev-devel
    - yajl
    - yajl-devel
    - asciidoc
    - perl-Pod-Simple
      #- docbook-style-xsl
    - pcre
    - startup-notification
    - startup-notification-devel
    - pango
    - pango-devel
    - cairo
    state: present

- name: make
  command:
    chdir: "{{ i3_src_path }}"
    command: /usr/bin/make

- name: make install
  become: yes
  command:
    chdir: "{{ i3_src_path }}"
    command: /usr/bin/make install
