---
- name: checkout fzf repo
  git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ fzf_path }}"
  register: fzf

- name: install/update fzf
  command:
    cmd: "{{ fzf_path }}/install"
  when: fzf.before != fzf.after
