---
- name: Install packages
  become: yes
  package:
    name:
    - git
    state: present

- name: Configure git
  template:
    src: "{{ item.src }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
  loop:
  - { src: 'dotgitconfig.j2', dest: '.gitconfig' }
  - { src: 'dotgitignore.j2', dest: '.gitignore' }
