---
- name: install bettercap build dependancies
  become: yes
  package:
    name:
    - build-essential
    - libpcap-dev
    - libusb-1.0-0-dev
    - libnetfilter-queue-dev
    state: latest

- name: determine latest bettercap version
  block:
  - github_release:
      user: bettercap
      repo: bettercap
      action: latest_release
    register: bettercap
  - set_fact:
      bettercap_version: "{{ bettercap.tag | regex_replace('^v', '') }}"
  when: bettercap_version in ['', 'latest']

- name: download bettercap release
  git:
    repo: "https://github.com/bettercap/bettercap.git"
    dest: "{{ ansible_user_dir }}/src/github.com/bettercap/bettercap"
    version: "v{{ bettercap_version }}"

- name: build bettercap from source
  command:
    cmd: make build
    chdir: "{{ ansible_user_dir }}/src/github.com/bettercap/bettercap"

- name: install bettercap
  become: yes
  command:
    cmd: make install
    chdir: "{{ ansible_user_dir }}/src/github.com/bettercap/bettercap"
