---
- name: install nfs-kernel-server
  become: yes
  package:
    name:
    - nfs-kernel-server
    state: latest
  notify:
  - restart nfsd

- name: create share directory
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 2770
    owner: 1000
    group: nogroup
  loop: nfsd_shares

- name: add folder to exports
  become: yes
  lineinfile:
    path: /etc/exports
    regexp: '^{{ item.path }}.*$'
    line: '{{ item.path }} {{ item.clients }}(rw,sync,anonuid=1000,anongid=65534,root_squash)'
  loop: nfsd_shares
  notify:
  - exportfs
