---
- name: add chrome apt keys
  become: yes
  apt_key:
    url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    state: present

- name: add chrome apt repo
  become: yes
  apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    state: present

- name: install chrome stable
  become: yes
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes
