---
- name: add chrome yum repo
  become: yes
  yum_repository:
    name: 'google-chrome'
    description: 'Official Chrome YUM repo.'
    baseurl: 'http://dl.google.com/linux/chrome/rpm/stable/$basearch'
    state: present
    gpgcheck: yes
    gpgkey: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

- name: install chrome stable
  become: yes
  yum:
    name: google-chrome-stable
    state: present
    update_cache: yes
