---
- name: install tmux package
  become: yes
  package:
    name:
    - tmux
    state: latest
    update_cache: yes

- name: install ~/.tmux.conf
  copy:
    src: "dottmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
