---
- name: install waybar via package
  become: yes
  package:
    name:
    - waybar
    state: latest

- name: create directories for waybar config and scripts
  file:
    state: directory
    path: "{{ item }}"
  loop:
  - "{{ ansible_user_dir }}/.config/waybar"
  - "{{ ansible_user_dir }}/scripts"

- name: install waybar config
  copy:
    content: "{{ waybar_config | to_nice_json }}"
    dest: "{{ ansible_user_dir }}/.config/waybar/config"
    mode: 0644

- name: install waybar style files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/waybar/{{ item | basename }}"
    mode: 0644
  with_fileglob: "{{ waybar_css_paths }}"

- name: install waybar module scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/scripts/{{ item | basename }}"
  with_fileglob: "{{ waybar_script_paths }}"
