---
- name: install waybar via package
  become: yes
  package:
    name:
    - waybar
    state: latest

- name: create waybar config directory
  file:
    state: directory
    path: "{{ ansible_user_dir }}/.config/waybar"

- name: install waybar config
  copy:
    content: "{{ waybar_config | to_nice_json }}"
    dest: "{{ ansible_user_dir }}/.config/waybar/config"
    mode: 0644

- name: install waybar style files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/waybar/{{ item | basename }}"
    mode: 0644
  with_fileglob: "{{ waybar_css_paths }}"
