---
- name: jupyter user/group setup
  become: yes
  when: jupyter_system_user
  block:
  - name: create jupyter system group
    group:
      name: "{{ jupyter_group }}"
      system: true
      state: present

  - name: create jupyter system user
    user:
      name: "{{ jupyter_user }}"
      system: true
      shell: "/usr/sbin/nologin"
      group: "{{ jupyter_group }}"
      create_home: false
      move_home: true
      home: "{{ jupyter_dir }}"

  - name: add user to jupyter group (requires user to log out/in)
    user:
      name: "{{ ansible_user }}"
      groups: "{{ jupyter_group }}"
      append: yes

- name: create jupyter data directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jupyter_user }}"
    group: "{{ jupyter_group }}"
    mode: 0770
  loop:
  - "{{ jupyter_dir }}"
  - "{{ jupyter_dir }}/notebooks"
  - "/etc/jupyter"

- name: Install jupyter in venv
  become: yes
  pip:
    name:
    - jupyter
    - jupyterthemes
    virtualenv: "{{ jupyter_venv }}"

- name: install python packages to use inside of jupyter
  become: yes
  pip:
    name: "{{ jupyter_packages }}"
    virtualenv: "{{ jupyter_venv }}"

- name: install jupyter config file
  become: yes
  template:
    src: jupyter_notebook_config.json.j2
    dest: "/etc/jupyter/jupyter_notebook_config.json"
    owner: "{{ jupyter_user }}"
    group: "{{ jupyter_group }}"
    mode: 0600

- name: create jupyter.service unit
  become: yes
  template:
    src: jupyter.service.j2
    dest: /etc/systemd/system/jupyter.service
    owner: root
    group: "{{ jupyter_group }}"
    mode: 0640
  notify:
  - restart jupyter.service
