---
- name: install_package_list
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - aptitude
  - dconf-editor
  - dstat
  - gimp
  - git
  - golang
  - htop
  - iotop
  - lsof
  - make
  - mercurial
  - openvpn
  - pandoc
  - pavucontrol
  - python-pip
  - tmux
  - tree
  - ssh
  - terminator
  - wget
