---
- name: install_package_list
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - aptitude
  - dconf-editor
  - gimp
  - golang
  - make
  - mercurial
  - openvpn
  - pandoc
  - pavucontrol
  - python-pip
