---
- name: install config files
  file:
    src: "{{ dotfiles }}/{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    state: link
  with_items: "{{ config_files }}"
  tags:
    - config

- name: create dir for css
  file:
    path: "{{ ansible_user_dir }}/css"
    state: directory

- name: download github css
  get_url:
    url: https://gist.githubusercontent.com/dashed/6714393/raw/ae966d9d0806eb1e24462d88082a0264438adc50/github-pandoc.css
    dest: "{{ ansible_user_dir }}/css/github-pandoc.css"
    mode: 0640

- name: disable desktop settings in dconf
  command: "dconf write {{ item }} false"
  with_items:
    - "/org/gnome/desktop/background/draw-background"
    - "/org/gnome/desktop/background/show-desktop-icons"
