---
- name: install config files
  file:
    src: "{{ dotfiles }}/{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    state: link
  with_items: "{{ config_files }}"
  tags:
    - config

- name: disable desktop settings in dconf
  command: "dconf write {{ item }} false"
  with_items:
    - "/org/gnome/desktop/background/draw-background"
    - "/org/gnome/desktop/background/show-desktop-icons"
