# vim:ft=ansible:
---
- name: add_apt_keys
  apt_key: url="{{ item }}" state=present
  with_items: apt_keys

- name: add_apt_repos
  apt_repository: repo="{{ item }}" state=present
  with_items: apt_repos

- name: apt-get_update
  apt: update_cache=yes

- name: install_package_list
  apt: name={{ item }} state=present
  with_items: apt_packages

- name: configure_git
  template: src=dotgitconfig dest={{ home }}/.gitconfig

- name: config_files
  file: src={{ dotfiles }}/{{ item.src }}
        dest={{ home }}/{{ item.dest }}
        state=link
  with_items: config_files

- name: checkout_pet_projects
  git: repo=git@github.com:{{ item.repo }}.git
       dest={{ src }}/{{ item.name }}
  with_items: personal_gits

- name: checkout_other_gits
  git: repo=https://github.com/{{ item.repo }}.git
       dest={{ src }}/{{ item.name }}
  with_items: other_gits

- name: install_fonts
  copy: src={{ fonts }}/ dest={{ user_fonts }} mode=0755

- name: reload_font_cache
  become: yes
  become_method: sudo
  command: fc-cache -f -v
