---
- name: add_apt_keys
  apt_key: url="{{ item }}" state=present
  with_items: apt_keys

- name: add_apt_repos
  apt_repository: repo="{{ item }}" state=present
  with_items: apt_repos

- name: apt-get_update
  apt: update_cache=yes

- name: install_package_list
  apt: name={{ item }} state=present
  with_items: apt_packages

- name: configure_git
  template: src=dotgitconfig dest={{ home }}/.gitconfig
