---
- name: install_package_list
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - dconf-editor
  - gimp
  - golang
  - make
  - mercurial
  - openvpn
  - pandoc
  - python-devel
  - python-pip
  - telnet

- name: remove_bashrc
  file:
    path: "{{ home }}/.bashrc"
    state: absent
