---
- name: install_package_list
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - dconf-editor
  - dstat
  - gimp
  - golang
  - htop
  - iotop
  - lsof
  - make
  - mercurial
  - openvpn
  - pandoc
  - python-devel
  - python-pip
  - telnet
  - tmux
  - tree
  - terminator
  - wget

- name: remove_bashrc
  file:
    path: "{{ home }}/.bashrc"
    state: absent
