---
- name: install system utilities
  become: yes
  package:
    name:
    - dstat
    - htop
    - iotop
    - lsof
    - tree
    - wget
    - telnet
    - make
    - zip
    - unzip
    - net-tools
    state: latest
