---
- name: add the docker apt gpg key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add the docker apt ppa
  become: yes
  apt_repository:
    repo: 'deb [arch={{ docker_arch[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
