# vim:ft=ansible:
- name: add_docker_gpg
  apt_key: url='hkp://pgp.mit.edu:80'
           id='58118E89F3A912897C070ADBF76221572C52609D'
           state=present

- name: add_docker_ppa
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-wily main'
                  state=present

- name: apt-get update
  apt: update_cache=yes

- name: install_docker_packages
  apt: name={{ item }}
       state=latest
  with_items: apt_packages

- name: add_user_to_docker_group (requires user to log out/in)
  user: name={{ user }}
        groups=docker
        append=yes

- name: install_docker-machine
  get_url: url=https://github.com/docker/machine/releases/download/v0.4.1/docker-machine_linux-amd64
           dest=/usr/local/bin/docker-machine
           mode=0755
           checksum="md5:93bfae4a59e75203e50154df075aa519"

- name: install_docker-compose
  pip: name=docker-compose
       state=latest
