---
- import_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- import_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: install docker packages
  become: yes
  package:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: yes
  notify:
  - restart docker

- name: add user to docker group (requires user to log out/in)
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user is defined

- block:
  - name: determine latest version of docker-machine
    github_release:
      user: docker
      repo: machine
      action: latest_release
    register: machine
  - set_fact:
      docker_machine_version: "{{ machine.tag }}"
  when: docker_machine_version in ['', 'latest']

- name: install docker-machine
  become: yes
  get_url:
    url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-Linux-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-machine
    mode: 0755

- name: install docker-compose
  become: yes
  pip:
    name:
    - docker-compose
    state: latest

- name: set aliases for long docker commands
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |-
      {% for key, val in docker_aliases.items() %}
      alias {{ key }}={{ val | regex_replace("^(.*)$", '"\1"') }}
      {% endfor %}
    marker: "# {mark} docker aliases"
