# vim:ft=ansible:
- name: Add docker gpg key
  apt_key: url='hkp://pgp.mit.edu:80'
           id='58118E89F3A912897C070ADBF76221572C52609D'
           state=present

- name: Add docker PPA
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-wily main'
                  state=present

- name: apt-get update
  apt: update_cache=yes

- name: Install package list
  apt: name={{ item }}
       state=latest
  with_items: apt_packages

- name: Add user to docker group (requires user to log out/in)
  user: name={{ user }}
        groups=docker
        append=yes

- name: Install docker-machine
  get_url: url=https://github.com/docker/machine/releases/download/v0.4.0/docker-machine_linux-amd64
           dest=/usr/local/bin/docker-machine
           mode=0755
           checksum="md5:71623840fb21a4234a24f96f78537275"

- name: Install docker-compose
  pip: name=docker-compose
       state=latest
