- fail:
    msg: this is untested

- name: add yum repo
  become: yes
  yum_repository:
    name: docker
    description: "Docker's official yum repo."
    baseurl: 'https://download.docker.com/linux/centos/docker-ce.repo'
    enabled: yes
    gpgcheck: yes
    gpgkey: 'https://yum.dockerproject.org/gpg'
