- name: add yum repo
  become: yes
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: 'https://download.docker.com/linux/centos/$releasever/$basearch/stable'
    enabled: yes
    gpgcheck: yes
    gpgkey: 'https://download.docker.com/linux/centos/gpg'
