---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: checkout_vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ home }}/.vim/bundle/Vundle.vim"

- name: vim_config
  template:
    src: dotvimrc
    dest: "{{ home }}/.vimrc"

- name: install_vim_plugins
  command: /usr/bin/vim +PluginInstall +qall
