---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: checkout_vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_user_dir }}/.vim/bundle/Vundle.vim"

- name: create dir for css
  file:
    path: "{{ ansible_user_dir }}/css"
    state: directory

- name: download github css
  get_url:
    url: https://gist.githubusercontent.com/dashed/6714393/raw/ae966d9d0806eb1e24462d88082a0264438adc50/github-pandoc.css
    dest: "{{ ansible_user_dir }}/css/github-pandoc.css"
    mode: 0640

- name: vim_config
  template:
    src: dotvimrc
    dest: "{{ ansible_user_dir }}/.vimrc"

- name: install_vim_plugins
  command: /usr/bin/vim +PluginInstall +qall
