# vim:ft=ansible:
apt_keys:
- 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

apt_repos:
- 'deb http://dl.google.com/linux/chrome/deb/ stable main'

apt_packages:
- aptitude
- dstat
- git
- golang
- google-chrome-stable
- htop
- iotop
- lsof
- make
- pavucontrol
- python-pip
- screen
#- spotify-client
- ssh
- terminator
- wget

dirs:
- "{{ home }}/.config/terminator"

config_files:
- { src: 'dotbashrc', dest: '.bashrc' }
- { src: 'dotgitignore', dest: '.gitignore' }
- { src: 'dotinputrc', dest: '.inputrc' }
- { src: 'dotconfig/terminator/config', dest: '.config/terminator/config' }

personal_gits:
- 'nicr9/daftpunk'
- 'nicr9/greptools'
- 'nicr9/lament'
- 'nicr9/otto'
- 'nicr9/pydialog'
- 'nicr9/vim-orca'

other_gits:
- 'larsenwork/monoid'
