# vim:ft=ansible:
apt_keys:
- 'https://dl-ssl.google.com/linux/linux_signing_key.pub'

apt_repos:
- 'deb http://ppa.launchpad.net/evarlast/golang1.4/ubuntu vivid main'
- 'deb http://dl.google.com/linux/chrome/deb/ stable main'

apt_packages:
- aptitude
- dstat
- git
- golang
- google-chrome-stable
- htop
- iotop
- lsof
- make
- pavucontrol
- python-pip
- screen
- spotify-client
- ssh
- terminator
- wget

dirs:
- "{{ home }}/.config/terminator"

config_files:
- { src: 'dotbashrc', dest: '.bashrc' }
- { src: 'dotgitignore', dest: '.gitignore' }
- { src: 'dotinputrc', dest: '.inputrc' }
- { src: 'dotconfig/terminator/config', dest: '.config/terminator/config' }

personal_gits:
- { repo: 'nicr9/daftpunk', name: 'daftpunk' }
- { repo: 'nicr9/greptools', name: 'greptools' }
- { repo: 'nicr9/lament', name: 'lament' }
- { repo: 'nicr9/otto', name: 'otto' }
- { repo: 'nicr9/pydialog', name: 'pydialog' }
- { repo: 'nicr9/vim-orca', name: 'vim-orca' }

other_gits:
- { repo: 'larsenwork/monoid', name: 'monoid' }
