dirs:
- "{{ home }}/.config/i3status"
- "{{ src }}"
- "{{ bin }}"
- "{{ patches }}"
- "{{ home }}/css"

config_files:
- { src: 'dotbashrc', dest: '.bashrc' }
- { src: 'dottmux', dest: '.tmux.conf' }
- { src: 'dotinputrc', dest: '.inputrc' }
- { src: 'dotconfig/i3status/config', dest: '.config/i3status/config' }
