---
- name: declare vim-plug plugins
  lineinfile:
    dest: "{{ nvim_config_path }}/plug.vim"
    state: present
    regexp: "^Plug '{{ repo }}'"
    line: "Plug '{{ repo }}'{% if options %}, {{ options | to_json | regex_replace('\"', \"'\") }}{% endif %}"

- name: plugin-specific config
  copy:
    content: "{{ config }}"
    dest: "{{ nvim_config_path }}/ansible-managed/{{ repo }}.vim"
  when: config is defined and config != ''
