---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: create autoload dir
  file:
    path: "{{ home }}/.local/share/nvim/site/autoload/"
    state: directory
    mode: 0750

- name: install vim-plug package manager into autoload
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0664

- name: ensure directory for nvim config exists
  file:
    path: "{{ xdg_config }}/nvim"
    state: directory

- name: copy nvim config file
  template:
    src: init.vim
    dest: "{{ xdg_config }}/nvim/init.vim"

- name: install plugins
  command: /usr/bin/nvim +PlugInstall +qall
