---
- include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
- include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: create autoload dir
  file:
    path: "{{ nvim_autoload_path }}/"
    state: directory
    mode: 0750

- name: install vim-plug package manager into autoload
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ nvim_autoload_path }}/plug.vim"
    mode: 0664

- name: ensure nvim config directories exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - '{{ nvim_config_path }}'
  - '{{ nvim_config_path }}/ftplugin'
  - '{{ nvim_config_path }}/ansible-managed'

- name: copy nvim config file
  template:
    src: init.vim.j2
    dest: "{{ nvim_config_path }}/init.vim"

- name: touch decoupled declarations config for vim-plug
  file:
    path: "{{ nvim_config_path }}/plug.vim"
    state: touch

- name: copy nvim ftplugin config
  copy:
    src: '{{ item }}'
    dest: "{{ nvim_config_path }}/ftplugin/{{ item | basename }}"
  with_fileglob:
  - 'ftplugin/*.vim'
  - 'nvim/ftplugin/*.vim'

- name: install plugins
  command: /usr/bin/nvim +PlugInstall +qall

- name: set nvim as default editor
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |-
      export EDITOR=nvim
      alias vim="nvim"
    marker: "# {mark} set nvim as default editor"
