- name: clone repos with interesting fonts
  git:
    repo: "https://github.com/{{ item.repo }}.git"
    dest: "{{ ansible_user_dir }}/src/github.com/{{ item.repo }}"
  loop: "{{ fonts_git }}"
  loop_control:
    label: "{{ item.repo }}"

- name: "copy git repo fonts to {{ fonts_install_path }}"
  become: yes
  copy:
    src: "{{ ansible_user_dir }}/src/github.com/{{ item.repo }}/{{ item.file }}"
    dest: "{{ fonts_install_path }}"
    mode: 0755
  loop: "{{ fonts_git }}"
  loop_control:
    label: "{{ item.repo }}/{{ item.file }}"

- name: install bundled fonts
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ fonts_install_path }}"
    mode: 0755
  loop:
  - monofur.otf

- name: reload font cache
  become: yes
  command: fc-cache -f -v
